// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 21/03/2025 9:20:27
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/nicolasbellina/Desktop/organisation/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/nicolasbellina/Desktop/organisation/frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/nicolasbellina/Desktop/organisation/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/nicolasbellina/Desktop/organisation/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/nicolasbellina/Desktop/organisation/frontend/plugins/**/*.{js,ts,mjs}","/Users/nicolasbellina/Desktop/organisation/frontend/composables/**/*.{js,ts,mjs}","/Users/nicolasbellina/Desktop/organisation/frontend/utils/**/*.{js,ts,mjs}","/Users/nicolasbellina/Desktop/organisation/frontend/pages/index.vue","/Users/nicolasbellina/Desktop/organisation/frontend/pages/stats.vue","/Users/nicolasbellina/Desktop/organisation/frontend/pages/todos.vue","/Users/nicolasbellina/Desktop/organisation/frontend/pages/users.vue","/Users/nicolasbellina/Desktop/organisation/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/nicolasbellina/Desktop/organisation/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/nicolasbellina/Desktop/organisation/frontend/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;